### ISSUE TITLE
How to add/remove tenants without stopping the NET Service? 

### ISSUE THREAD

**Issue by ZedZipDev** [zahidcakici/MultitenatFinbuckleExample#2]
If I have N tenants working with NET Service how can I add the new (N+1)th tenant/remove and existing tenant without breaking the existing clients , i.e. without restarting the NET Service?

**Comment by zahidcakici** [comment]
You can use one of the Multitenant Stores strategies according to your specific case. You can access stores at runtime by using Service Provider. 
```
// Assume we have a service provider. The IEnumerable could be injected via
// other DI means as well.
var store = serviceProvider.GetService<IEnumerable<IMultiTenantStore<TenantInfo>>>
                           .Where(s => s.ImplementationType == typeof(InMemoryStore))
                           .SingleOrDefault();

// Add some tenants...
await store.TryAddAsync(new TenantInfo{...});

// Update a tenant.
newTenant.ConnectionString = "UpdatedConnectionString";
await store.TryUpdateAsync(newTenant);

// Remove a tenant.
await store.TryRemoveAsync(newTenant.Identifier);
```
You may use In-Memory Store which is used in this repository. But remember it is volatile! As a real case scenario I guess EFCore Store would be very useful. If you implement a Microservices architecture then Http Remote Store can be good choice. Or you can even use multiple store :) 
For more information please check [this documentation](https://www.finbuckle.com/MultiTenant/Docs/v6.10.0/Stores).
